[package]
name = "mcts"
version = "0.1.0"
authors = ["prestonmlangford <prestonmlangford@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
time = "0.1"
rand_core = "0.6.1"
rand = "0.6"

[lib]
name = "mcts"
path = "src/lib.rs"
