[workspace]
resolver = "2"

members = [
    "arbor",
    "mancala",
    "reversi",
    "connect4",
    "tictactoe",
    "www",
]

[profile.release]
opt-level = 3

[profile.release.package.tictactoe]
# Tell `rustc` to optimize for small code size.
opt-level = "s"